### ISSUE TITLE
Ordering of symbols

### ISSUE THREAD

**Issue by davemacdo** [fkretlow/figurato#1]
Following up on the discussion from the Dorico boards, I wanted to put an issue about the order here on GH for discussion. 

In the US, we usually speak and write about figures from the top-down (even though everything else in harmony goes the other direction). I don't know what the best solution for the font would be if this was a thing you want to focus on. 

Do you think it makes sense to create an alternate .otf file that goes top-to-bottom, and folks can choose the one that makes the most sense to the way they use the symbols? 

If I know where to look in the SFD file, perhaps I could try to work on this issue.

**Comment by davemacdo** [comment]
Following up, I discovered that you have already changed the file to spell top-to-bottom. Thanks!

However, in doing so, it seems there is now an issue with placing an accidental alone on the bottom row. Doing this results in the last accidental being shifted to the right, rather than in a vertical line with the rest of the figures.

**Comment by fkretlow** [comment]
Yes, I have decided to change the direction to top-to-bottom. I think I have already fixed the issue with single accidentals. I'll upload the fix when I have a chance, perhaps next week. (I'm traveling right now.)

Also, in the meantime I've been in touch with Daniel and it seems like there's a bug in the Qt framework that messes up any vertical positioning in opentype fonts in the Mac version of Dorico. He has forwarded this to the Qt developers, but I don't know if it is going to be fixed anytime soon. Fortunately the wrong behavior is predictable: all y values in a value record are simply inverted, so I should be able to create a second otf file that creates the expected order of the figures for Dorico on Mac.

Unless someone really wants the old bottom-up direction I guess there's no point in providing different versions of the font for that reason only. But it might be worth the effort to create a top-down version that aligns all figures on the bottom row, for figured bass above the system. I'll see. 

In which software and OS have you tried the font, David?

With the next upload I'll add the feature code as separate (commented) .fea files because creating positioning and substitution features such as these within Fontforge is really awkward. That should make it easier for others to contribute.

**Comment by davemacdo** [comment]
I'm using Dorico 2 Pro on a Mac. I think I was mistaken. It reads as top to bottom in the editor, but then it is flipped when printed out. I'm not sure there's anything the font can do to fix that. I haven't tried Figurato in Sibelius Ultimate.

**Comment by fkretlow** [comment]
David, what you see is that with the current version in Dorico on Mac the figures are stacked top-down, but bottom-up when printed, is that correct? If so, then you're probably right that a different version of the font for Mac won't help.
Could you send me a screenshot and a corresponding pdf so I can see what happens in terms of horizontal alignment of multiple figures?

This issue is becoming quite irritating...

**Comment by davemacdo** [comment]
Here's a screenshot. On the left is Dorico (Print mode, but it looks the same everywhere). On the right is a screenshot of the PDF of this page.

<img width="553" alt="screen shot 2018-08-26 at 8 34 20 am" src="https://user-images.githubusercontent.com/6425544/44628716-20832480-a90b-11e8-96ee-a396e9ed11ca.png">

Here's the PDF.

[test.pdf](https://github.com/fkretlow/figurato/files/2321542/test.pdf)

**Comment by fkretlow** [comment]
Damn it!!

The order in the pdf is 'correct': it shows the positioning that I would expect from the current version of the font. (I changed the direction to top-down but I haven't uploaded this version yet.) But of course Dorico positions the whole figure according to how its own layout engine interprets the positioning feature, hence the collision.

I don't think there's anything I can do about it. What a shame!

**Comment by fkretlow** [comment]
With FiguratoMac this should not be a problem anymore.

**Comment by composerjk** [comment]
> Also, in the meantime I've been in touch with Daniel and it seems like there's a bug in the Qt framework that messes up any vertical positioning in opentype fonts in the Mac version of Dorico. He has forwarded this to the Qt developers, but I don't know if it is going to be fixed anytime soon. Fortunately the wrong behavior is predictable: all y values in a value record are simply inverted, so I should be able to create a second otf file that creates the expected order of the figures for Dorico on Mac.

Note that the Qt developers finally [fixed the bug](https://bugreports.qt.io/browse/QTBUG-69803). There was old code inverting the Y scale on macOS. Hopefully Dorico will incorporate the Qt version with the fix, soon (if they haven't already). I have not yet tested Dorico 2.2 (built 4 days after the bug report was closed) to check if the fix was included.

**Comment by fkretlow** [comment]
> Note that the Qt developers finally [fixed the bug](https://bugreports.qt.io/browse/QTBUG-69803). There was old code inverting the Y scale on macOS. Hopefully Dorico will incorporate the Qt version with the fix, soon (if they haven't already). I have not yet tested Dorico 2.2 (built 4 days after the bug report was closed) to check if the fix was included.

Thanks, Jeff. That’s good to know. Philip tested the font in Dorico 2.2 on Mac today and it looks like the fix hasn’t made it into the released build. We’ll have to wait for the next builds then.

**Comment by fkretlow** [comment]
I've had word from Daniel Spreadbury. Dorico won't incorporate a new version of the Qt framework before the next major update in 2019.

**Comment by composerjk** [comment]
Thanks for the updates, Florian.

**Comment by fkretlow** [comment]
With the release of Dorico 3 this issue has become moot. I’m closing it now.
