### ISSUE TITLE
Strange behaviour with Dorico

### ISSUE THREAD

**Issue by Kirckman** [fkretlow/figurato#4]
Dear Florian,

Congratulations to your font, I really enjoy using it, thanks for creating it!

I experienced two issues when using it with Dorico (Windows 10):

1. It seems that the font has a different mapping compared to the manual:
The different kinds of modified numbers, with normal slashes (/), with tiny slashes (' and '') and ligatures with + doesn't seem to work, however their glyphs do appear when I type the normal slashes, as follows:

2/ = 2 ligature with +
3/ = 3 with normal slash (however the placing is incorrect)
4/ = 4 ligature with +
5/ = 5 ligature with +
6/ = 6 with tiny slash
7/ = 7 with tiny slash
9/ = 9 with tiny slash

2. The placing of an accidental (without a number in the row) under a number with an accidental is incorrect: however, when the accidental is under a number without an accidental, the placing is correct.

I attach some screenshots for clarification.

All good wishes,
K

![fig01](https://user-images.githubusercontent.com/62537261/77294371-7769ff00-6ce4-11ea-8cbc-bbb2617e1250.png)
![fig02](https://user-images.githubusercontent.com/62537261/77294376-789b2c00-6ce4-11ea-813e-d7ac62926cb6.png)
![fig03](https://user-images.githubusercontent.com/62537261/77294377-789b2c00-6ce4-11ea-9c2b-669ee4060a76.png)
![fig04](https://user-images.githubusercontent.com/62537261/77294379-7933c280-6ce4-11ea-9675-3acc3d94fc7b.png)
![fig05](https://user-images.githubusercontent.com/62537261/77294380-7933c280-6ce4-11ea-9c6b-50999559859d.png)
![fig06](https://user-images.githubusercontent.com/62537261/77294381-79cc5900-6ce4-11ea-9efd-a58d1575beec.png)

**Comment by fkretlow** [comment]
Thanks for the feedback! I’m glad you like the font.

Are you sure you are using the right version of the font? These are old mappings. It looks like you're  using either an old version of Figurato, or FiguratoMac. Make sure you select Figurato or FiguratoB.

As for the misplaced accidentals: There are two things going on here, one of which is a misunderstanding, the other a real bug.
1. `,` advances the input to the next row, but if the previous row is full already (e.g. it has a number and some sort of quality indication), the 'cursor' has jumped already. Typing `,` makes it jump once more. `6ss` should give you what you want in the second example above.
2. Unfortunately there seems to be no way to get the same thing with two b-flats. Normally, `,` should only break the ligature bb and not make you jump to the next row. This is a bug.

It’s been a veeeery long time since I’ve worked on the feature code. I’ll look into fixing this, but I can't make any promises. It’ll take some time because I’ll need to re-study the code (it’s very obscure and convoluted because of the limitations of the platform).

**Comment by Kirckman** [comment]
Dear Florian,

Thanks for your message! It's a new PC and I've just downloaded Figurato a few days ago so it must be the latest version I guess. How can I check this?

Yes, after I sent the message, I realized that the sharps and naturals are working fine (e.g. 6ss & 6nn).

It would be amazing if you could fix the b-flats too I'm doing a lot of basso continuo stuff with Dorico (I'm a harpsichordist) and I would be very pleased if you could fix this bug sometime!

All good wishes,
K

**Comment by fkretlow** [comment]
Could you accidentally have used FiguratoMac? I think it's still part of the release package although it's not really needed anymore.

**Comment by Kirckman** [comment]
Hi Florian,

No, I used the windows version (Figurato.otf).

K

**Comment by Kirckman** [comment]
Dear Florian,

Please could you send me the most recent windows version of the font, as what I downloaded (however it seems to be the latest version - I downloaded it again and reinstalled the font to be sure) keeps showing the old mappings in Dorico.

All best,
K

**Comment by fkretlow** [comment]
The binaries in the repository are the latest, there are no others.

However, something else might be at play here. Windows sometimes fails to correctly overwrite installed fonts when you install a new version. Could you please try the following steps:

1. Remove all versions of Figurato that you have currently installed. There may be multiple versions sitting on top of each other, be sure to delete all of them.

2. Rebuild the font cache as described here: https://winaero.com/blog/rebuild-font-cache-windows-10/

3. Restart the system. Make sure it actually reboots, don't just send it to hibernate.

4. Reinstall only `Figurato.otf` from the latest release and report back if it still doesn't work.

**Comment by Kirckman** [comment]
Dear Florian,

Thank you so much, deleting and re-installing the font - surprisingly - has finally worked! I say surprisingly because I only started to use your font a few days before I first wrote to you so actually I never had any previous version installed on my PC!

Anyway, thank you so much!
All good wishes,
Augustin

**Comment by fkretlow** [comment]
Okay, that's good to hear. I'll close this then.
