### ISSUE TITLE
Opening bracket quirk

### ISSUE THREAD

**Issue by BC16661** [fkretlow/figurato#7]
Hi
I am inputting editorial figured bass for a client using Figurato in Sibelius Ultimate. To distinguish it from the original, he wants an opening bracket before the first added symbol and a closing one after the last. I input [5 6 6] and the output is correct EXCEPT that the opening bracket before the 5 extends down as if there were a second figure below it... If I input [5], the brackets are perfect.

![image](https://user-images.githubusercontent.com/126015420/220434869-ae2870f6-0b4f-47e3-87dd-7a5c123e08bf.png)

Any help gratefully accepted :)
Best wishes,
Brian

**Comment by fkretlow** [comment]
Hi Brian,

Thanks for reporting the issue. I can reproduce it. In fact, I'm wondering why this wasn't noticed before.

However, since the addition of figured bass to Dorico I consider Figurato deprecated. Fixing this issue would be rather involved. If I happen to have the time I'll look into it, but don't hold your breath. For the time being the best workaround might be to add the brackets as separate text objects.

Best wishes,
Florian

**Comment by fkretlow** [comment]
As it happens, I just looked at the manual and found out that there is a way to do this: https://github.com/fkretlow/figurato/blob/master/docs/manual.md#parentheses-and-brackets

Let me know if this fixes your issue.

**Comment by BC16661** [comment]
Hi Florian!
Thanks for getting back to me.
It took a moment for me to realise that the manual link was to the section
that showed how using | "terminates" an open bracket! Brilliant!
Thanks,
Brian
